apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  namespace: app
  name: vault-kvv2-app
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # name of the secret
  name: webapp/config

  # dest k8s secret
  destination:
    name: secretkvv2
    create: true
  # static secret refresh interval
  refreshAfter: 30s